ALTER TABLE "OtherInvoice" ADD COLUMN IF NOT EXISTS "adjustments" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "OtherInvoice" ADD COLUMN IF NOT EXISTS "terms" TEXT;
ALTER TABLE "OtherInvoiceItem" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "OtherInvoiceItem" ADD COLUMN IF NOT EXISTS "discountType" TEXT NOT NULL DEFAULT 'FLAT';
ALTER TABLE "OtherInvoiceItem" ADD COLUMN IF NOT EXISTS "taxPercent" DECIMAL(12,2) NOT NULL DEFAULT 0;