/**
 * Center Manager catalog item → permission mappings (mirrors backend permission-catalog.ts).
 * Used for sidebar visibility (read) and page edit controls (write).
 */
export const CENTER_ITEM_READ_PERMISSIONS: Record<string, string[]> = {
  "leads.all": ["lead.read"],
  "leads.new": ["lead.read"],
  "leads.ai_calling": ["ai_call.read"],
  "leads.followups": ["lead.read"],
  "leads.call_history": ["ai_call.read", "lead.read"],
  "admissions.enquiries": ["lead.read"],
  "admissions.applications": ["admission.read"],
  "admissions.all": ["admission.read"],
  "admissions.direct": ["admission.read"],
  "admissions.documents": ["document.read"],
  "counsellor.all": ["user.read"],
  "counsellor.lead_allocation": ["lead.read"],
  "counsellor.performance": ["target.read", "report.read"],
  "students.all": ["student.read"],
  "students.documents": ["document.read"],
  "students.student_allocation": ["batch.read", "student.read"],
  "students.attendance": ["attendance.read"],
  "students.performance": ["student.read", "report.read"],
  "students.discontinuation": ["student.read"],
  "faculty.all": ["faculty.read"],
  "faculty.attendance": ["attendance.read"],
  "faculty.performance": ["feedback.read", "report.read"],
  "courses.all": ["course.read"],
  "courses.curriculum": ["module.read", "course.read"],
  "courses.modules": ["module.read"],
  "courses.course_assignment": ["faculty.read", "course.read"],
  "batches.all": ["batch.read"],
  "schedule.timetable": ["schedule.read"],
  "schedule.classes": ["schedule.read"],
  "schedule.live": ["schedule.read", "google_meet.read"],
  "schedule.recordings": ["recording.read"],
  "assignments.all": ["assignment.read"],
  "assignments.create": ["assignment.read"],
  "assignments.submissions": ["assignment.read"],
  "assignments.reviews": ["assignment.read"],
  "exams.all": ["exam.read"],
  "exams.create": ["exam.read"],
  "exams.question_bank": ["question_bank.read"],
  "exams.results": ["exam.read", "exam.view_attempts"],
  "fees.plans": ["fee.read"],
  "fees.student_fees": ["fee.read"],
  "fees.payments": ["fee.read"],
  "fees.pending": ["fee.read"],
  "fees.receipts": ["fee.read"],
  "fees.reports": ["fee.read", "report.read"],
  "targets.all": ["target.read"],
  "targets.assignments": ["target.read"],
  "targets.leaderboard": ["target.read", "incentive.read"],
  "targets.incentives": ["incentive.read"],
  "reports.students": ["report.read"],
  "reports.admissions": ["report.read", "admission.read"],
  "reports.attendance": ["report.read", "attendance.read"],
  "reports.faculty": ["report.read"],
  "reports.courses": ["report.read"],
  "reports.examinations": ["report.read", "exam.read"],
  "reports.financial": ["report.read", "fee.read"],
  "communication.notifications": ["notification.read"],
  "communication.whatsapp": ["notification.read"],
  "communication.email": ["email.read"],
  "communication.automation": ["notification.read"],
  "placement.eligible": ["placement.read"],
  "placement.companies": ["placement.read"],
  "placement.jobs": ["placement.read"],
  "placement.applications": ["placement.read"],
  "placement.interviews": ["placement.read"],
  "placement.placements": ["placement.read"],
  "admin.organization": ["institute.read"],
  "admin.branches": ["branch.read"],
  "admin.masters": ["master.read"],
  "admin.integrations": ["integration.read", "google_meet.read"],
  "admin.settings": ["institute.read"],
};

export const CENTER_ITEM_WRITE_PERMISSIONS: Record<string, string[]> = {
  "leads.all": ["lead.create", "lead.update", "lead.assign", "lead.convert", "lead.delete"],
  "leads.new": ["lead.create"],
  "leads.ai_calling": ["ai_call.create"],
  "leads.followups": ["lead.update", "lead.assign"],
  "leads.call_history": [],
  "admissions.enquiries": ["lead.create", "lead.update"],
  "admissions.applications": ["admission.create", "admission.update"],
  "admissions.all": ["admission.create", "admission.update"],
  "admissions.direct": ["admission.create", "admission.update"],
  "admissions.documents": ["document.create", "document.verify", "document.update"],
  "counsellor.all": ["user.create", "user.update"],
  "counsellor.lead_allocation": ["lead.assign", "lead.update"],
  "counsellor.performance": [],
  "students.all": ["student.create", "student.update"],
  "students.documents": ["document.create", "document.verify", "document.update"],
  "students.student_allocation": ["batch.update"],
  "students.attendance": ["attendance.mark", "attendance.update"],
  "students.performance": [],
  "students.discontinuation": ["student.update"],
  "faculty.all": ["faculty.create", "faculty.update"],
  "faculty.attendance": ["attendance.mark", "attendance.update"],
  "faculty.performance": [],
  "courses.all": ["course.create", "course.update"],
  "courses.curriculum": ["module.create", "module.update"],
  "courses.modules": ["module.create", "module.update"],
  "courses.course_assignment": ["faculty.update", "batch.update"],
  "batches.all": ["batch.create", "batch.update"],
  "schedule.timetable": ["schedule.update"],
  "schedule.classes": ["schedule.create", "schedule.update", "schedule.delete"],
  "schedule.live": ["google_meet.create", "schedule.update"],
  "schedule.recordings": ["recording.create", "recording.delete"],
  "assignments.all": ["assignment.create", "assignment.update", "assignment.delete"],
  "assignments.create": ["assignment.create"],
  "assignments.submissions": ["assignment.grade"],
  "assignments.reviews": ["assignment.grade", "assignment.update"],
  "exams.all": ["exam.create", "exam.update", "exam.publish"],
  "exams.create": ["exam.create", "exam.schedule", "exam.assign"],
  "exams.question_bank": ["question_bank.create", "question_bank.update", "question_bank.delete"],
  "exams.results": ["exam.update"],
  "fees.plans": ["fee.update"],
  "fees.student_fees": ["fee.update"],
  "fees.payments": ["fee.create"],
  "fees.pending": ["fee.update"],
  "fees.receipts": [],
  "fees.reports": [],
  "targets.all": ["target.manage", "target.assign"],
  "targets.assignments": ["target.assign"],
  "targets.leaderboard": [],
  "targets.incentives": ["target.approve"],
  "reports.students": [],
  "reports.admissions": [],
  "reports.attendance": [],
  "reports.faculty": [],
  "reports.courses": [],
  "reports.examinations": [],
  "reports.financial": [],
  "communication.notifications": ["notification.manage"],
  "communication.whatsapp": ["notification.resend", "notification.manage"],
  "communication.email": ["email.manage"],
  "communication.automation": ["notification.manage"],
  "placement.eligible": [],
  "placement.companies": ["placement.create", "placement.update"],
  "placement.jobs": ["placement.create", "placement.update"],
  "placement.applications": ["placement.create", "placement.update"],
  "placement.interviews": ["placement.create", "placement.update"],
  "placement.placements": ["placement.create", "placement.update"],
  "admin.organization": [],
  "admin.branches": ["branch.update"],
  "admin.masters": ["master.create", "master.update", "master.delete"],
  "admin.integrations": ["integration.manage", "google_meet.connect"],
  "admin.settings": ["institute.update"],
};

/** Legacy module keys for modulePermissions fallback (maps ERP groups). */
export const CENTER_MODULE_LEGACY_KEYS: Record<string, string> = {
  lead_management: "leads_ai_calling",
  admission_management: "admissions",
  counsellor_management: "counsellor",
  student_management: "students",
  faculty_management: "faculty",
  course_management: "courses",
  batch_management: "batches",
  class_schedule: "schedule",
  assignment_management: "assignments",
  examination_management: "examinations",
  fee_management: "fees",
  target_incentive: "targets",
  report_management: "reports",
  communication: "notifications",
  placement_management: "placement",
  administration: "masters",
};

export const canReadCenterItem = (
  permissions: string[] | undefined,
  itemKey: string
): boolean => {
  if (!permissions?.length) return false;
  const required = CENTER_ITEM_READ_PERMISSIONS[itemKey];
  if (!required?.length) return false;
  const permSet = new Set(permissions);
  return required.some((p) => permSet.has(p));
};

export const canEditCenterItem = (
  permissions: string[] | undefined,
  itemKey: string
): boolean => {
  if (!permissions?.length) return false;
  const readOk = canReadCenterItem(permissions, itemKey);
  if (!readOk) return false;
  const writePerms = CENTER_ITEM_WRITE_PERMISSIONS[itemKey];
  if (!writePerms?.length) return false;
  const permSet = new Set(permissions);
  return writePerms.every((p) => permSet.has(p));
};
