export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    ASK_ME: "/admin/ask-me",
    HOME: "/admin/home",
    LEADS: {
      ROOT: "/admin/leads",
      NEW: "/admin/leads/new",
      DETAIL: (id: string) => `/admin/leads/${id}`,
      AI_CALLING: "/admin/leads/ai-calling",
      FOLLOW_UPS: "/admin/leads/follow-ups",
      CALL_HISTORY: "/admin/leads/call-history",
    },
    ADMISSIONS: {
      ENQUIRIES: "/admin/admissions/enquiries",
      APPLICATIONS: "/admin/admissions/applications",
      ALL: "/admin/admissions/all",
      DIRECT: "/admin/admissions/direct-entry",
      DOCUMENTS: "/admin/admissions/documents",
    },
    COUNSELLORS: {
      ALL: "/admin/counsellors",
      LEAD_ALLOCATION: "/admin/counsellors/lead-allocation",
      PERFORMANCE: "/admin/counsellors/performance",
    },
    STUDENTS: {
      ALL: "/admin/students/all",
      DETAIL: (id: string) => `/admin/students/${id}`,
      DOCUMENTS: "/admin/students/documents",
      STUDENT_ALLOCATION: "/admin/students/student-allocation",
      /** @deprecated Use STUDENT_ALLOCATION */
      BATCH_ALLOCATION: "/admin/students/student-allocation",
      ATTENDANCE: "/admin/students/attendance",
      PERFORMANCE: "/admin/students/performance",
      DISCONTINUATION: "/admin/students/discontinuation-risk",
    },
    BATCHES: {
      ALL: "/admin/batches",
      CREATE: "/admin/batches",
      DETAIL: (id: string) => `/admin/batches/${id}`,
      /** @deprecated Use COURSES.COURSE_ASSIGNMENT or batch details */
      FACULTY_ALLOCATION: "/admin/courses/course-assignment",
    },
    FACULTY: {
      ALL: "/admin/faculty/all",
      DETAIL: (id: string) => `/admin/faculty/${id}`,
      /** @deprecated Faculty assign at batch create / course assignment / batch details */
      FACULTY_ALLOCATION: "/admin/courses/course-assignment",
      /** @deprecated Use FACULTY_ALLOCATION */
      BATCH_ASSIGNMENT: "/admin/courses/course-assignment",
      /** @deprecated moved to Course Management */
      COURSE_ASSIGNMENT: "/admin/courses/course-assignment",
      ATTENDANCE: "/admin/faculty/attendance",
      PERFORMANCE: "/admin/faculty/performance",
    },
    COURSES: {
      ALL: "/admin/courses/all",
      DETAIL: (id: string) => `/admin/courses/${id}`,
      CURRICULUM: "/admin/courses/curriculum",
      MODULES: "/admin/courses/modules",
      COURSE_ASSIGNMENT: "/admin/courses/course-assignment",
    },
    SCHEDULE: {
      TIMETABLE: "/admin/schedule/timetable",
      CLASSES: "/admin/schedule/classes",
      LIVE: "/admin/schedule/live",
      RECORDINGS: "/admin/schedule/recordings",
    },
    ASSIGNMENTS: {
      ALL: "/admin/assignments",
      CREATE: "/admin/assignments/create",
      DETAIL: "/admin/assignments/:id",
      SUBMISSIONS: "/admin/assignments/submissions",
      REVIEWS: "/admin/assignments/reviews",
    },
    EXAMS: {
      ALL: "/admin/exams",
      CREATE: "/admin/exams/create",
      QUESTION_BANK: "/admin/exams/question-bank",
      RESULTS: "/admin/exams/results",
    },
    FEES: {
      PLANS: "/admin/fees/plans",
      STUDENT_FEES: "/admin/fees/student-fees",
      PAYMENTS: "/admin/fees/payments",
      PENDING: "/admin/fees/pending",
      RECEIPTS: "/admin/fees/receipts",
      REPORTS: "/admin/fees/reports",
    },
    TARGETS: {
      ALL: "/admin/targets",
      ASSIGNMENTS: "/admin/targets/assignments",
      LEADERBOARD: "/admin/targets/leaderboard",
      INCENTIVES: "/admin/targets/incentives",
    },
    REPORTS: {
      STUDENTS: "/admin/reports/students",
      ADMISSIONS: "/admin/reports/admissions",
      ATTENDANCE: "/admin/reports/attendance",
      FACULTY: "/admin/reports/faculty",
      COURSES: "/admin/reports/courses",
      EXAMINATIONS: "/admin/reports/examinations",
      FINANCE: "/admin/reports/finance",
    },
    COMMUNICATION: {
      NOTIFICATIONS: "/admin/communication/notifications",
      WHATSAPP: "/admin/communication/whatsapp",
      EMAIL: "/admin/communication/email",
      AUTOMATION: "/admin/communication/automation",
    },
    PLACEMENT: {
      ELIGIBLE: "/admin/placement/eligible",
      COMPANIES: "/admin/placement/companies",
      JOBS: "/admin/placement/jobs",
      APPLICATIONS: "/admin/placement/applications",
      INTERVIEWS: "/admin/placement/interviews",
      PLACEMENTS: "/admin/placement/placements",
    },
    ADMINISTRATION: {
      ORGANIZATION: "/admin/administration/organization",
      BRANCHES: "/admin/administration/branches",
      USERS: "/admin/administration/users",
      ROLES: "/admin/administration/roles",
      MASTERS: "/admin/administration/masters",
      INTEGRATIONS: "/admin/administration/integrations",
      BILLING: "/admin/administration/billing",
      AUDIT_LOGS: "/admin/administration/audit-logs",
      SETTINGS: "/admin/administration/settings",
    },
  },
  CENTER: {
    DASHBOARD: "/center/dashboard",
    BRANCHES: "/center/branches",
    BATCHES: "/center/batches",
  },
  COUNSELOR: {
    DASHBOARD: "/counselor/dashboard",
    LEADS: "/counselor/leads",
    ADMISSIONS: "/counselor/admissions",
  },
  FACULTY: {
    DASHBOARD: "/faculty/dashboard",
    CLASSES: "/faculty/classes",
    ATTENDANCE: "/faculty/attendance",
    ASSIGNMENTS: {
      ALL: "/faculty/assignments",
      CREATE: "/faculty/assignments/create",
      DETAIL: (id: string) => `/faculty/assignments/${id}`,
      SUBMISSIONS: "/faculty/assignments/submissions",
      REVIEWS: "/faculty/assignments/reviews",
    },
  },
  STUDENT: {
    DASHBOARD: "/student/dashboard",
    SCHEDULE: "/student/schedule",
    RECORDINGS: "/student/recordings",
    ASSIGNMENTS: "/student/assignments",
    CERTIFICATES: "/student/certificates",
  },
};
